import type { NextPage } from 'next'
import Head from 'next/head'
import { Flex } from "@chakra-ui/layout"
import styles from "../styles/Home.module.css"
import React from "react"
import { Hero } from "../components/molecules/Hero/Hero"
import { TopBar } from "../components/organisms/TopBar/TopBar"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SuperApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <Flex>
        <Hero />
      </Flex>
    </div>
  )
}

export default Home
